Select personID, firstName, lastName from Person where
(firstName like 'Vanessa' and lastName like 'Peabody') or
(firstName like 'Erin' and lastName like 'Jaurigue') or
(firstName like 'David' and lastName like 'Northfield') or
(firstName like 'Emily' and lastName like 'Nathoo') or
(firstName like 'Ashley' and lastName like 'Barton') or
(firstName like 'Destiny' and lastName like 'Purnum') or
(firstName like 'Pamela' and lastName like 'Stoltz') or
(firstName like 'Joe' and lastName like 'McCray') or
(firstName like 'Shannon' and lastName like 'Effler') or
(firstName like 'Mary' and lastName like 'Hansen') or
(firstName like 'Karyn-Lynn' and lastName like 'Fisette') or
(firstName like 'Mary' and lastName like 'Welch') or
(firstName like 'Danielle' and lastName like 'Moore') or
(firstName like 'Lisa' and lastName like 'Levine') or
(firstName like 'Dallis' and lastName like 'Gilbert') or
(firstName like 'Deborah' and lastName like 'Ellis') or
(firstName like 'Abigail' and lastName like 'Quaterman') or
(firstName like 'John' and lastName like 'Perley') or
(firstName like 'Nicole' and lastName like 'Rooney') or
(firstName like 'Sharon' and lastName like 'Burgess') or
(firstName like 'Jessica' and lastName like 'Adamson') or
(firstName like 'Arica' and lastName like 'Focer') or
(firstName like 'Lindsey' and lastName like 'Mains') or
(firstName like 'Jay' and lastName like 'Cunningham') or
(firstName like 'Jaime' and lastName like 'Daignault') or
(firstName like 'Ava' and lastName like 'Archuleta') or
(firstName like 'Jen' and lastName like 'McIntosh') or
(firstName like 'Michelle' and lastName like 'Afroso') or
(firstName like 'Westie' and lastName like 'Hennessy') or
(firstName like 'Daniel' and lastName like 'Waldeck') or
(firstName like 'Austin' and lastName like 'Grant') or
(firstName like 'Wendy' and lastName like 'Keith') or
(firstName like 'Karen' and lastName like 'Bernius') or
(firstName like 'Fritz' and lastName like 'Mitas') or
(firstName like 'Claire' and lastName like 'Love') or
(firstName like 'Gina' and lastName like 'Easley') or
(firstName like 'Chelsea' and lastName like 'Jay') or
(firstName like 'Kaitlyn' and lastName like 'Stoll') or
(firstName like 'Stephanie' and lastName like 'Feurestein') or
(firstName like 'Jessica' and lastName like 'Adams') or
(firstName like 'Jeff' and lastName like 'Johnson') or
(firstName like 'Peter' and lastName like 'Hamilton') or
(firstName like 'Brad' and lastName like 'Ross') or
(firstName like 'Colleen' and lastName like 'Kellog') or
(firstName like 'Danny' and lastName like 'Asbury') or
(firstName like 'Kelly' and lastName like 'Reck') or
(firstName like 'Ashley' and lastName like 'Soares') or
(firstName like 'Mary' and lastName like 'Charles') or
(firstName like 'Rachel' and lastName like 'Robinson') or
(firstName like 'Bethany' and lastName like 'Burgee') or
(firstName like 'Jenna' and lastName like 'LaMere') or
(firstName like 'Stephanie' and lastName like 'Anderson') or
(firstName like 'Sarah' and lastName like 'Yu') or
(firstName like 'Jenna' and lastName like 'Perry') or
(firstName like 'Laura' and lastName like 'La Londe') or
(firstName like 'Heidi' and lastName like 'Liere') or
(firstName like 'Erin' and lastName like 'Zintek') or
(firstName like 'Mark' and lastName like 'Spangler') or
(firstName like 'Yolan' and lastName like 'Baker') or
(firstName like 'Chelsea' and lastName like 'Sandbloom') or
(firstName like 'Rick' and lastName like 'Morris') or
(firstName like 'Will' and lastName like 'Rausch') or
(firstName like 'Caitlin' and lastName like 'Coffman') or
(firstName like 'Jen' and lastName like 'Mashburn') or
(firstName like 'Stephanie' and lastName like 'Goodwin') or
(firstName like 'Suzie' and lastName like 'Fujioka') or
(firstName like 'Jacque' and lastName like 'Hayes') or
(firstName like 'Penelope' and lastName like 'Manalili') or
(firstName like 'Stephanie' and lastName like 'Windham') or
(firstName like 'Sandra' and lastName like 'Coveny') or
(firstName like 'Marisha' and lastName like 'Knutson') or
(firstName like 'Jessica' and lastName like 'Garcia') or
(firstName like 'Beth' and lastName like 'Iversen') or
(firstName like 'Robert' and lastName like 'Bastian') or
(firstName like 'Atira' and lastName like 'Casburn') or
(firstName like 'April' and lastName like 'Ozuna') or
(firstName like 'Ellen' and lastName like 'Carder') or
(firstName like 'Benjamin' and lastName like 'Sigman') or
(firstName like 'Cari' and lastName like 'Wells') or
(firstName like 'Helga' and lastName like 'Pratt') or
(firstName like 'Arlene' and lastName like 'Holmes') or
(firstName like 'Tonya' and lastName like 'DeCrose') or
(firstName like 'Erik' and lastName like 'Lawrence') or
(firstName like 'Robin' and lastName like 'Cunningham') or
(firstName like 'Carmela' and lastName like 'Web') or
(firstName like 'Lynette' and lastName like 'Davis') or
(firstName like 'Charlotte' and lastName like 'Compa') or
(firstName like 'Katherine' and lastName like 'Carley') or
(firstName like 'Lisa' and lastName like 'Gray') or
(firstName like 'Annabelle' and lastName like 'Araya') or
(firstName like 'Jamie' and lastName like 'Boyda') or
(firstName like 'Kate' and lastName like 'Laudermilk') or
(firstName like 'Katharine' and lastName like 'Nester') or
(firstName like 'James' and lastName like 'Hilliard') or
(firstName like 'Julie' and lastName like 'Stahl') or
(firstName like 'Jennifer' and lastName like 'Williamson') or
(firstName like 'Jessica' and lastName like 'Taber') or
(firstName like 'Vincent' and lastName like 'Ethier') or
(firstName like 'Lucinda' and lastName like 'Bowman') or
(firstName like 'John' and lastName like 'Gaunt') or
(firstName like 'Kathleen' and lastName like 'Sligar') or
(firstName like 'Shaun' and lastName like 'Daley') or
(firstName like 'Andy' and lastName like 'Coulomba') or
(firstName like 'Shoshana' and lastName like 'Lund') or
(firstName like 'Terrie' and lastName like 'Verotsky') or
(firstName like 'Amy' and lastName like 'Lyden') or
(firstName like 'Bruce' and lastName like 'Kingman') or
(firstName like 'Mark' and lastName like 'Pasadilla') or
(firstName like 'Brooke' and lastName like 'Galloway') or
(firstName like 'Akemi' and lastName like 'Ishikawa') or
(firstName like 'Catherine' and lastName like 'Band') or
(firstName like 'Melisse' and lastName like 'De La More') or
(firstName like 'Briana' and lastName like 'Dumas') or
(firstName like 'Amber' and lastName like 'Roberts') or
(firstName like 'Nicole' and lastName like 'Nakano') or
(firstName like 'Danella' and lastName like 'Kawachi') or
(firstName like 'Nicole' and lastName like 'Shaw') or
(firstName like 'Michael' and lastName like 'Shoaee') or
(firstName like 'Bob' and lastName like 'Streicher') or
(firstName like 'Haley' and lastName like 'Scavone') or
(firstName like 'Connie' and lastName like' UNKNOWN') or
(firstName like 'Marijke' and lastName like 'Weaver ') or
(firstName like 'James' and lastName like 'Toothacker') or
(firstName like 'Trudi' and lastName like 'Krajewski') or
(firstName like 'Kelsey' and lastName like 'Koehler') or
(firstName like 'Christine' and lastName like 'UNKNOWN') or
(firstName like 'Valerie' and lastName like 'UNKNOWN') or
(firstName like 'Valerie' and lastName like 'Doran') or
(firstName like 'Ryan' and lastName like 'Gallop') or
(firstName like 'Laurie' and lastName like 'Hill ') or
(firstName like 'Nicole' and lastName like 'Gauthier') or
(firstName like 'Tami' and lastName like 'Matthews') or
(firstName like 'Todd' and lastName like 'Waddell ') or
(firstName like 'Marji' and lastName like 'Thimpson') or
(firstName like 'Keith' and lastName like 'Spande') or
(firstName like 'Venetia' and lastName like 'Mayhew') or
(firstName like 'Heather' and lastName like 'Conradt') or
(firstName like 'Misty' and lastName like 'Amweg') or
(firstName like 'Jenniefer' and lastName like 'Sharp') or
(firstName like 'Andrea' and lastName like 'Tuson') or
(firstName like 'John' and lastName like 'Mato') or
(firstName like 'Judy' and lastName like 'Caldwell') or
(firstName like 'Michael' and lastName like 'Parsons') or
(firstName like 'Callie' and lastName like 'Nelson') or
(firstName like 'Jami' and lastName like 'Wray') or
(firstName like 'Sande' and lastName like 'LeBlanc') or
(firstName like 'Jane' and lastName like 'Perkins') or
(firstName like 'Kris' and lastName like 'Calvert') or
(firstName like 'Nicole' and lastName like 'Shapport') or
(firstName like 'Ryan' and lastName like 'Mitchell') or
(firstName like 'Gerald' and lastName like 'Beever') or
(firstName like 'Frank' and lastName like 'Brown') or
(firstName like 'Dorothy' and lastName like 'Sikora') or
(firstName like 'Jordan' and lastName like 'Daleson') or
(firstName like 'Vincent' and lastName like 'Clementi') or
(firstName like 'Zev' and lastName like 'Gabai') or
(firstName like 'Carmen' and lastName like 'Kintz') or
(firstName like 'Erin' and lastName like 'Lima') or
(firstName like 'Tracy' and lastName like 'paradis') or
(firstName like 'Breanna' and lastName like 'Steele') or
(firstName like 'Fabien' and lastName like 'Mills') or
(firstName like 'Jessica' and lastName like 'Munsch') or
(firstName like 'Nicole' and lastName like 'Gilmore') or
(firstName like 'Belle' and lastName like 'Bezdicek') or
(firstName like 'Paula' and lastName like 'Little') or
(firstName like 'Lindsay' and lastName like 'Gill') or
(firstName like 'Sharon' and lastName like 'Davis') or
(firstName like 'Courtney' and lastName like 'Baggett') or
(firstName like 'Kristena' and lastName like 'Mirbelka') or
(firstName like 'Michelle' and lastName like 'Bechler') or
(firstName like 'Lindsay' and lastName like 'Lindala') or
(firstName like 'George' and lastName like 'Janis') or
(firstName like 'Ashley' and lastName like 'Roland') or
(firstName like 'Lisa' and lastName like 'Carder') or
(firstName like 'Brittny' and lastName like 'Cole') or
(firstName like 'Adam' and lastName like 'Nimmo') or
(firstName like 'Laurie' and lastName like 'Ramsey') or
(firstName like 'Christy' and lastName like 'Sweaney') or
(firstName like 'Lucas' and lastName like 'Servera') or
(firstName like 'Jennifer' and lastName like 'Hogan') or
(firstName like 'Adrienne' and lastName like 'Bridge') or
(firstName like 'Tonya' and lastName like 'Fuerte') or
(firstName like 'Laura' and lastName like 'Rigler') or
(firstName like 'Amy' and lastName like 'Kaupp');

